<def f='halide/llvm-install/include/llvm/Support/Error.h' l='557' ll='562' type='llvm::Error llvm::Expected::takeError()'/>
<use f='halide/llvm-install/include/llvm/Object/ObjectFile.h' l='301' u='c' c='_ZNK4llvm6object10ObjectFile19getCommonSymbolSizeENS0_11DataRefImplE'/>
<use f='halide/llvm-install/include/llvm/Object/ObjectFile.h' l='463' u='c' c='_ZNK4llvm6object10SectionRef11getContentsEv'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/JITSymbol.h' l='349' u='c' c='_ZN4llvm9JITSymbol10getAddressEv'/>
<use f='halide/llvm-install/include/llvm/Object/Archive.h' l='170' u='c' c='_ZN4llvm6object7Archive21ChildFallibleIterator3incEv'/>
<doc f='halide/llvm-install/include/llvm/Support/Error.h' l='553'>/// Take ownership of the stored error.
  /// After calling this the Expected&lt;T&gt; is in an indeterminate state that can
  /// only be safely destructed. No further calls (beside the destructor) should
  /// be made on the Expected&lt;T&gt; value.</doc>
<use f='halide/src/Introspection.cpp' l='933' u='c' c='_ZN6Halide8Internal13Introspection12_GLOBAL__N_113DebugSections26load_and_parse_object_fileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/LLVM_Output.cpp' l='158' u='c' c='_ZN6Halide8Internal7Archive12_GLOBAL__N_118write_symbol_tableERSoRKSt6vectorIN4llvm16NewArchiveMemberESaIS6_EEbPSt3mapImS4_INS2_9PatchInfoESaISC_EESt45819532'/>
<use f='halide/src/LLVM_Output.cpp' l='164' u='c' c='_ZN6Halide8Internal7Archive12_GLOBAL__N_118write_symbol_tableERSoRKSt6vectorIN4llvm16NewArchiveMemberESaIS6_EEbPSt3mapImS4_INS2_9PatchInfoESaISC_EESt45819532'/>
<use f='halide/src/LLVM_Output.cpp' l='560' u='c' c='_ZN6Halide21create_static_libraryERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EERKNS_6TargetERKS6_b'/>
