<dec f='include/python3.8/pyerrors.h' l='160' type='PyObject * PyErr_SetFromErrnoWithFilenameObjects(PyObject * , PyObject * , PyObject * )'/>
