<dec f='llvm/build/projects/libcxx/include/c++build/cxxabi.h' l='43' type='void * __cxxabiv1::__cxa_allocate_exception(size_t thrown_size)'/>
<doc f='llvm/build/projects/libcxx/include/c++build/cxxabi.h' l='41'>// 2.4.2 Allocating the Exception Object</doc>
<dec f='llvm/libcxxabi/include/cxxabi.h' l='43' type='void * __cxxabiv1::__cxa_allocate_exception(size_t thrown_size)'/>
<doc f='llvm/libcxxabi/include/cxxabi.h' l='41'>// 2.4.2 Allocating the Exception Object</doc>
<def f='llvm/libcxxabi/src/cxa_exception.cpp' l='183' ll='197' type='void * __cxxabiv1::__cxa_allocate_exception(size_t thrown_size)'/>
<doc f='llvm/libcxxabi/src/cxa_exception.cpp' l='178'>//  Allocate a __cxa_exception object, and zero-fill it.
//  Reserve &quot;thrown_size&quot; bytes on the end for the user&apos;s exception
//  object. Zero-fill the object. If memory can&apos;t be allocated, call
//  std::terminate. Return a pointer to the memory to be used for the
//  user&apos;s exception object.</doc>
