<dec f='llvm/libcxxabi/src/cxa_exception.h' l='26' type='uint64_t __cxxabiv1::__getExceptionClass(const _Unwind_Exception * )'/>
<use f='llvm/libcxxabi/src/cxa_default_handlers.cpp' l='43' u='c' c='_ZL28demangling_terminate_handlerv'/>
<def f='llvm/libcxxabi/src/cxa_exception.cpp' l='95' ll='103' type='uint64_t __cxxabiv1::__getExceptionClass(const _Unwind_Exception * unwind_exception)'/>
<use f='llvm/libcxxabi/src/cxa_exception.cpp' l='106' u='c' c='__cxxabiv1::__isOurExceptionClass'/>
<use f='llvm/libcxxabi/src/cxa_exception.cpp' l='111' u='c' c='__cxxabiv1::isDependentException'/>
<doc f='llvm/libcxxabi/src/cxa_exception.cpp' l='94'>//  Is it one of ours?</doc>
<use f='llvm/libcxxabi/src/cxa_personality.cpp' l='504' u='c' c='__cxxabiv1::get_thrown_object_ptr'/>
<use f='llvm/libcxxabi/src/cxa_personality.cpp' l='1180' u='c' c='__cxxabiv1::__cxa_call_unexpected'/>
