<dec f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.h' l='667' type='void lldb_private::python::PythonException::Restore()'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.h' l='700' u='c' c='_ZN12lldb_private6python26unwrapOrSetPythonExceptionEN4llvm8ExpectedIT_EE'/>
<def f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1045' ll='1052' type='void lldb_private::python::PythonException::Restore()'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/ScriptInterpreterPython.cpp' l='1074' u='c' c='_ZN12lldb_private27ScriptInterpreterPythonImpl24ExecuteOneLineWithReturnEN4llvm9StringRefENS_17ScriptInterpreter16ScriptReturnTypeEPvRKNS3_20ExecuteScriptOptionsE'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/ScriptInterpreterPython.cpp' l='1189' u='c' c='_ZN12lldb_private27ScriptInterpreterPythonImpl20ExecuteMultipleLinesEPKcRKNS_17ScriptInterpreter20ExecuteScriptOptionsE'/>
