<dec f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.h' l='672' type='std::string lldb_private::python::PythonException::ReadBacktrace() const'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='79839' u='c' c='LLDBSwigPythonCreateScriptedThreadPlan'/>
<def f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1084' ll='1103' type='std::string lldb_private::python::PythonException::ReadBacktrace() const'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/ScriptInterpreterPython.cpp' l='1187' u='c' c='_ZN12lldb_private27ScriptInterpreterPythonImpl20ExecuteMultipleLinesEPKcRKNS_17ScriptInterpreter20ExecuteScriptOptionsE'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/ScriptInterpreterPython.cpp' l='2310' u='c' c='_ZN12lldb_private27ScriptInterpreterPythonImpl26BreakpointCallbackFunctionEPvPNS_24StoppointCallbackContextEmm'/>
<use f='llvm/lldb/unittests/ScriptInterpreter/Python/PythonDataObjectsTests.cpp' l='813' u='a' c='_ZN41PythonDataObjectsTest_TestExceptions_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/ScriptInterpreter/Python/PythonDataObjectsTests.cpp' l='833' u='a' c='_ZN41PythonDataObjectsTest_TestExceptions_Test8TestBodyEv'/>
