<dec f='llvm/build/include/c++/v1/future' l='576' type='void std::__1::__assoc_sub_state::set_exception_at_thread_exit(std::exception_ptr __p)'/>
<def f='llvm/libcxx/src/future.cpp' l='121' ll='129' type='void std::__1::__assoc_sub_state::set_exception_at_thread_exit(std::exception_ptr __p)'/>
<use f='llvm/libcxx/src/future.cpp' l='255' u='c' c='_ZNSt3__17promiseIvE28set_exception_at_thread_exitESt13exception_ptr'/>
