<dec f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.h' l='661' type='PyObject *'/>
<offset>256</offset>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1016' u='r' c='_ZNK12lldb_private6python15PythonException9toCStringEv'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1018' u='r' c='_ZNK12lldb_private6python15PythonException9toCStringEv'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1023' u='w' c='_ZN12lldb_private6python15PythonExceptionC1EPKc'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1030' u='w' c='_ZN12lldb_private6python15PythonExceptionC1EPKc'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1031' u='r' c='_ZN12lldb_private6python15PythonExceptionC1EPKc'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1058' u='r' c='_ZN12lldb_private6python15PythonExceptionD1Ev'/>
