<dec f='include/python3.8/pyerrors.h' l='157' type='PyObject * PyErr_SetFromErrnoWithFilenameObject(PyObject * , PyObject * )'/>
