<dec f='include/python3.8/pyerrors.h' l='77' type='PyObject *'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='900' u='r' c='_ZL21SWIG_Python_ErrorTypei'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='85799' u='r' c='_ZL20swig_varlink_getattrP18swig_varlinkobjectPc'/>
<use f='llvm/build/tools/lldb/bindings/python/LLDBWrapPython.cpp' l='85816' u='r' c='_ZL20swig_varlink_setattrP18swig_varlinkobjectPcP7_object'/>
