<inh f='llvm/build/include/c++/v1/exception' l='99' c='std::exception'/>
<def f='llvm/build/include/c++/v1/variant' l='225' ll='228'/>
<use f='llvm/build/include/c++/v1/variant' l='244' c='_ZNSt3__126__throw_bad_variant_accessEv'/>
<size>8</size>
<fun r='_ZNKSt18bad_variant_access4whatEv'/>
