<dec f='include/python3.8/pyerrors.h' l='34' type='int PyErr_GivenExceptionMatches(PyObject * , PyObject * )'/>
<doc f='include/python3.8/pyerrors.h' l='33'>/* Error testing and normalization */</doc>
<use f='halide/build/_deps/pybind11-src/include/pybind11/pytypes.h' l='363' u='c' c='_ZNK8pybind1117error_already_set7matchesENS_6handleE'/>
