<dec f='include/python3.8/pyerrors.h' l='86' type='PyObject *'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/common.h' l='724' u='r' c='_ZNK8pybind1111index_error9set_errorEv'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/internals.h' l='235' u='r' c='_ZN8pybind116detail19translate_exceptionENSt15__exception_ptr13exception_ptrE'/>
